services:
  mongo:
    container_name: mongo-server
    image: mongo:3.6
    restart: always
    volumes:
      - /Users/lincenying/web/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

  api:
    container_name: api-server
    image: lincenying/api-server:1.0.0
    environment:
      DATABASE_URL: mongodb://mongo:27017
    ports:
      - 4008:4000
    depends_on:
      - mongo
    networks:
      - webnet

  app:
    container_name: images-mmf-blog-vite-vue3-ssr
    image: lincenying/images-mmf-blog-vite-vue3-ssr:1.0.1
    environment:
      API_URL: http://api:4000
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - 7777:7777
    networks:
      - webnet

  nuxt:
    container_name: images-mmf-blog-vite-nuxt
    image: lincenying/images-mmf-blog-vite-nuxt:1.0.2
    environment:
      NUXT_ENV_API_URL: http://api:4000
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - 7200:7200
    networks:
      - webnet

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - api app nuxt
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d

networks:
  webnet:
    driver: bridge
