services:
  mongo:
    container_name: dc-db-mongo
    image: mongo:4.0
    volumes:
      - ${MONGO_DIR:-./data/mongodb}:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

  mysql:
    container_name: dc-db-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-database_name}
      MYSQL_USER: ${MYSQL_USER:-MYSQL_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-MYSQL_password}
    ports:
      - "3306:3306"
    volumes:
      - ./web/mysql:/app/mysql
      - ${MYSQL_DIR:-./data/mysqldb}:/var/lib/mysql
    networks:
      - webnet

  api:
    container_name: dc-api-express
    image: lincenying/api-express:${API_EXPRESS_TAG}
    environment:
      DATABASE_URL: mongodb://mongo:27017
    ports:
      - 4000:4000
    depends_on:
      - mongo
    networks:
      - webnet

  app:
    container_name: dc-app-vue3-ssr
    image: lincenying/app-vue3-ssr:${APP_VUE3_SSR_TAG}
    environment:
      API_URL: http://api:4000
    env_file:
      - .env
    depends_on:
      - api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 7777:7777
    networks:
      - webnet

  nuxt:
    container_name: dc-app-nuxt
    image: lincenying/app-nuxt:${APP_NUXT_TAG}
    environment:
      NUXT_ENV_API_URL: http://api:4000
    env_file:
      - .env
    depends_on:
      - api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 7200:7200
    networks:
      - webnet

  app_php:
    container_name: dc-app-php
    image: lincenying/app-php:${APP_PHP_TAG}
    networks:
      - webnet
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:-database_name}
      DB_USERNAME: ${MYSQL_USER:-MYSQL_user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-MYSQL_password}
    env_file:
      - .env

  nginx_php:
    container_name: dc-nginx-php
    image: lincenying/nginx-php:${APP_PHP_TAG}
    ports:
      - "8084:80"
    networks:
      - webnet
    depends_on:
      - app_php

  nginx:
    container_name: dc-nginx
    image: nginx:alpine
    depends_on:
      - api
      - app
      - nuxt
      - nginx_php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d.alias:/etc/nginx/conf.d
      - ./nginx/cong.d.php/php.alias.conf:/etc/nginx/conf.d/php.conf
      - ./nginx/cert:/etc/nginx/cert
      - ./web:/home/web
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
