services:
  mongo:
    container_name: dc-mongo-server
    image: mongo:4.0
    volumes:
      - /Users/lincenying/web/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

  api:
    container_name: dc-api-server
    image: lincenying/api-server:1.25.1029
    environment:
      DATABASE_URL: mongodb://mongo:27017
    ports:
      - 4008:4000
    depends_on:
      - mongo
    networks:
      - webnet

  app:
    container_name: dc-app-vue3-ssr
    image: lincenying/images-mmf-blog-vite-vue3-ssr:1.25.1029
    environment:
      API_URL: http://api:4000
    env_file:
      - .env
    depends_on:
      - api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 7777:7777
    networks:
      - webnet

  nuxt:
    container_name: dc-app-nuxt
    image: lincenying/images-mmf-blog-vite-nuxt:1.25.1029
    environment:
      NUXT_ENV_API_URL: http://api:4000
    env_file:
      - .env
    depends_on:
      - api
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 7200:7200
    networks:
      - webnet

  nginx:
    container_name: dc-nginx
    image: nginx
    depends_on:
      - api
      - app
      - nuxt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d.alias:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./web:/home/web
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
