[Definition]
failregex = ^<HOST> .* "(GET|POST|HEAD|PUT|DELETE) .*(?:\.env|/\.git|wp-admin|wp-login\.php|xmlrpc\.php|phpmyadmin|adminer|vendor/phpunit|actuator|/solr/|manager/html|/cgi-bin/|\.aws/|etc/passwd|_ignition|telescope|\.htaccess|\.htpasswd).*"
ignoreregex =
