server {
    listen 80;
    #listen 443 ssl;
    server_name www.test.com;

    # 腾讯云
    #ssl_certificate cert/www.test.com_bundle.crt;
    #ssl_certificate_key cert/www.test.com.key;
    #ssl_protocols TLSv1.2 TLSv1.3;
    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    # 阿里云
    #ssl_certificate cert/www.test.com.pem;
    #ssl_certificate_key cert/www.test.com.key;
    #ssl_session_cache shared:SSL:1m;
    #ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;

    #ssl_session_timeout 5m;
    #ssl_prefer_server_ciphers on;

    #if ($scheme = http) {
    #    return 301 https://$host$request_uri;
    #}

    location ^~ /api/ {
        # api 是后端 API 的 service name, 4000 是容器端口
        proxy_pass http://api:4000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host  $http_host;
        proxy_set_header X-Nginx-Proxy true;
        proxy_set_header Connection "";
    }

    location / {
        # app 是 vue3-ssr 的 service name, 7777 是容器端口
        proxy_pass http://app:7777;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host  $http_host;
        proxy_set_header X-Nginx-Proxy true;
        proxy_set_header Connection "";
    }
}

