server {
    listen 80;
    server_name py.test.com;

    include /etc/nginx/conf.d/anti-scan.inc;

    location / {
        proxy_pass http://upstream_python;
        include /etc/nginx/conf.d/proxy-params.inc;
    }
}
