server {
    listen 80;
    #listen 443 ssl;
    server_name api.test.com;

    # 腾讯云
    #ssl_certificate cert/api.test.com_bundle.crt;
    #ssl_certificate_key cert/api.test.com.key;
    #ssl_protocols TLSv1.2 TLSv1.3;
    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    # 阿里云
    #ssl_certificate cert/api.test.com.pem;
    #ssl_certificate_key cert/api.test.com.key;
    #ssl_session_cache shared:SSL:1m;
    #ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;

    #ssl_session_timeout 5m;
    #ssl_prefer_server_ciphers on;

    location / {
        # dc-api-express是后端API容器的container_name, 4000是后端API容器的端口号
        proxy_pass http://dc-api-express:4000;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host  $http_host;
        proxy_set_header X-Nginx-Proxy true;
        proxy_set_header Connection "";
    }
}

