server {
    listen 80;
    #listen 443 ssl;
    server_name api.test.com;

    include /etc/nginx/conf.d/anti-scan.inc;

    # 腾讯云
    #ssl_certificate cert/api.test.com_bundle.crt;
    #ssl_certificate_key cert/api.test.com.key;
    #ssl_protocols TLSv1.2 TLSv1.3;
    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    # 阿里云
    #ssl_certificate cert/api.test.com.pem;
    #ssl_certificate_key cert/api.test.com.key;
    #ssl_session_cache shared:SSL:1m;
    #ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;

    #ssl_session_timeout 5m;
    #ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://upstream_api;
        include /etc/nginx/conf.d/proxy-params.inc;
    }
}
