server {
    listen 80;
    server_name demo-h5.test.com; # 替换为你的域名
    root /home/web/demo-h5;

    include /etc/nginx/conf.d/anti-scan.inc;

    location ^~ /api/ {
        proxy_pass http://upstream_api;
        include /etc/nginx/conf.d/proxy-params.inc;
    }

    location / {
        index index.html;
        try_files $uri $uri/ /index.html =404;
    }
}
